projectglow/glow

docs/source/api/glue-functions.rst, docs/source/index.rst
Glue function docs:
- subset_struct
- add_struct_fields
- expand_struct
- array_to_dense_vector
- array_to_sparse_vector
- vector_to_array
- explode_matrix
- genotype_states
- hard_calls
```
cd docs
make html
open build/html/index.html
```
=> [HLS-353] Add utility function docs

core/src/main/scala/io/projectglow/sql/expressions/MomentAggState.scala, core/src/main/scala/io/projectglow/sql/expressions/PerSampleSummaryStatistics.scala, core/src/main/scala/io/projectglow/sql/expressions/SampleCallSummaryStats.scala, core/src/main/scala/io/projectglow/sql/util/ExpectsGenotypeFields.scala, core/src/main/scala/io/projectglow/transformers/normalizevariants/VariantNormalizer.scala, core/src/test/scala/io/projectglow/tertiary/SampleQcExprsSuite.scala
Now that https://github.com/apache/spark/pull/25666 has merged, it's more convenient and performant to return an array and filter by index. In addition, we can now generate sample qc stats when we don't have sample ids, which we expect to be the common case.
(Details)
=> Make sample qc exprs return an array instead of a map

docs/README.md, docs/source/conf.py, python/environment.yml
See title!
Made sure the theme looks right locally.
=> Use the readthedocs sphinx theme

README.md
Add PyPi and Maven Central badges to README.
=> Add PyPi and Maven Central badges to README

build.sbt
Adds the Git hash to the MANIFEST file. We do so by adding it directly to the Manifest attributes in the `core` project. We shell out to git to get the current HEAD commit.
=> Include the Git Hash in the MANIFEST file

docs/source/_static/css/glow.css, docs/source/conf.py, docs/source/index.rst, docs/source/troubleshooting.rst, version.sbt
We can add to this as we find new common issues.
(Details)
=> Add a troubleshooting doc

docs/extensions/notebook.py, docs/source/additional-resources.rst
Adds a link to the notebooks to explain how to run Databricks notebooks.
Resolves https://github.com/projectglow/glow/issues/36.
=> Add docs to run Databricks notebooks

build.sbt
In #37 @jpdna reported an error when using `spark-submit`'s maven resolver to install glow. This error occurs because the resolver doesn't seem to work with dependencies with a classifier.
I resolved the issue by excluding the native netlib libraries. Besides resolving this particular issue, this change follows the pattern established by mllib where users must explicitly opt into using the native extensions.
Verified that `sbt dependencyTree` no longer contains any of the netlib native libraries.
=> Exclude netlib libraries from GATK dependency

core/src/test/scala/io/projectglow/tertiary/VariantQcExprsSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFFileWriterSuite.scala
Sometimes in tests we use `show()` to force materialization of a dataframe. This pattern makes the test logs really noisy. Instead, we can just call `.collect()` to force materialization.
(Details)
Test logs should be clean now.
=> Replace df.show() with df.collect()

core/src/main/scala/io/projectglow/sql/SqlExtensionProvider.scala, core/src/main/scala/io/projectglow/sql/expressions/AggregateByIndex.scala, core/src/main/scala/io/projectglow/sql/optimizer/hlsOptimizerRules.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/org/apache/spark/sql/SQLUtils.scala, core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala, core/src/test/scala/io/projectglow/tertiary/AggregateByIndexSuite.scala
We currently include a few functions to compute sample-based quality control statistics. However, users can't write their own functions that aggregate across the same dimension without getting intimately familiar with Spark internals.
This PR adds a function,  `aggregate_by_index`, that provides the scaffolding for users to write their own aggregations. The user provides an initial value, an update function to merge a buffer object with a new datum, a merge function to combine two buffers, and optionally an evaluate function called on the buffer to produce a result. These arguments are analogous to those of the `aggregate` higher order function built into Spark: https://docs.databricks.com/_static/notebooks/apache-spark-2.4-functions.html.
I'll provide documentation for the new function …
=> Function to aggregate across all elements at each index in array columns

core/src/main/scala/io/projectglow/bgen/BgenFileFormat.scala, core/src/main/scala/io/projectglow/bgen/BgenSchemaInferrer.scala, core/src/main/scala/io/projectglow/common/datasourceOptions.scala, core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/test/scala/io/projectglow/bgen/BgenReaderSuite.scala
Previously, if a BGEN file contained sampleIds, they were always included in the emitted DataFrame. If a user didn't want them (common when dealing with large cohort sizes), they had to manually drop them.
Now, you can provide the same `includeSampleIds` option used by the VCF and Plink datasources. If it is `false`, sample ids are not included in the output.
cc @emaxwell 
(Details)
=> Add BGEN option to explicitly not include sample ids

docs/source/conf.py
The Databricks site is experiencing some server issues. To un-break the build, we can just ignore linkchecking there for now.
`make linkcheck` works again!
=> Don't linkcheck for databricks.com

core/src/main/scala/io/projectglow/transformers/pipe/PipeTransformer.scala, core/src/test/scala/io/projectglow/transformers/pipe/PipeTransformerSuite.scala
Throws clearer exceptions if the pipe input or output formatter are not provided.
=> Cleaner error messaging if pipe input/output formatter not provided

build.sbt, core/src/main/scala/io/projectglow/common/GlowLogging.scala
During my changes in https://github.com/projectglow/glow/pull/68, I depended on a different subpackage of the Scala logger in anticipation of cross-building with Scala 2.12. We did not cross-build but the Scala logger subpackage change was not reverted; this PR reverts that.
=> Depend on slf4j

core/src/main/scala/io/projectglow/common/WithUtils.scala
Writing with the big VCF datasource results in OOMs and/or an exorbitant amount of GC when we cache in memory if the DataFrame to be written is large. Even if we cache as `MEMORY_AND_DISK`, we can still run out of heap space as executors drop off before they can fall back to caching on disk. Caching on disk is probably the safest option.
Tested with a variety of storage levels; `DISK_ONLY` is the only one that works even when there is a very limited amount of memory (a single c5.xlarge worker).
=> Persist RDDs and Datasets on disk by default

core/src/main/scala/io/projectglow/vcf/BigVCFDatasource.scala, core/src/test/scala/io/projectglow/vcf/VCFFileWriterSuite.scala
#67 results in an empty vcf file if an empty dataframe is passed along with a determined header to bigvcf writer. This PR adds a condition to fix this, i.e., make sure the header is written although the DataFrame is empty. Also if number of partitions is 0 (which can happen) an appropriate message is emitted.
=> Fix for bigvcf writer with a header but no rows

docs/source/index.rst
Adds documentation links to Glow homepage and Github page.
`make livehtml` looks good!
=> Add links to Glow sites

docs/source/conf.py
Reverts https://github.com/projectglow/glow/pull/70 now that the Databricks site appears to be stable.
`curl -I https://databricks.com` works reliably.
=> Linkcheck databricks.com

core/src/main/scala/io/projectglow/Glow.scala, core/src/main/scala/io/projectglow/sql/SqlExtensionProvider.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/org/apache/spark/sql/SQLUtils.scala, core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala, docs/source/conf.py, docs/source/getting-started.rst, docs/source/tertiary/pipe-transformer.rst, docs/source/tertiary/variant-normalization.rst, python/environment.yml, python/glow/glow.py, python/glow/tests/test_register.py
When Glow is attached as a library (vs. being baked into a Spark runtime), we need to inject the rules in addition to registering the extensions. As the rules are needed for the extensions to function properly, it makes sense for simplicity's sake to perform the injection during the `glow.register(spark)` step. This PR also exposes the same `Glow.register(spark)` API in Scala, and simplifies documentation for Scala users by creating distinct Python/Scala tabs for language-specific docs.
Resolves https://github.com/projectglow/glow/issues/86.
Replicated the attached issue in a Jupyter notebook. After running the following step in a cell:
```
spark.sparkContext._jvm.io.projectglow.sql.GlowSQLExtensions().apply(spark._jsparkSession.extensions())
```
The command succeeded.
=> Inject Spark session rules during SQL extension registration

core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala
`VCFPiperSuite` can be flaky with leaked file streams occurring during `createVCFCodec`. Making sure all the streams created there are wrapped will keep this from occurring.
Hopefully CircleCI fails less.
=> Wrap closeable VCF stream

core/src/test/scala/io/projectglow/plink/PlinkReaderSuite.scala
Allows us to be compatible with libraries that depend on Glow and run our tests, even if they wrap our exceptions. To do so, we can check if any exception in a stack has the expected type + message.
=> Check for nested exceptions

core/src/main/scala/io/projectglow/vcf/VariantContextToInternalRowConverter.scala, core/src/test/scala/io/projectglow/vcf/VariantContextToInternalRowConverterSuite.scala
Sometimes, VariantContext array-based attributes are stored as a comma-separated string. This currently breaks the `VariantContextToInternalRowConverter` if the validation stringency is strict, and incorrectly sets the field to `null` otherwise.
=> Parse INFO attribute arrays from strings

core/src/main/scala/io/projectglow/vcf/TabixIndexHelper.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala, core/src/test/scala/io/projectglow/vcf/TabixHelperSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala
Previously we checked whether a .vcf.gz file was block gzipped in `VCFFileFormat.isSplittable`. Although this location is logically the right place, Spark runs this code on each file serially. Since checking whether a file is gzipped or block gzipped requires reading the part of the file, this process can be very slow on large datasets.
Instead, we now handle the difference between gz and bgz while reading files. If we detect that a file is gzipped, we read the entire file if the current split starts at the beginning of the file and read nothing if it starts in the middle. Note that this is not the ideal behavior since we're creating a ton of tasks that do nothing. However, in the common case where .gz actually means block gzip, we can now …
=> Move gzip check to file reading

core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala, core/src/test/scala/io/projectglow/vcf/TabixHelperSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFHeaderUtilsSuite.scala
This makes it easier to call into from places where you might not have FileStatuses.
(Details)
=> Take strings instead of FileStatuses in VCFHeaderUtils

core/src/test/scala/io/projectglow/vcf/VCFPiperSuite.scala
I believe that the test could previously fail because the output formatter would throw an exception while the input formatter still had a stream open. Now, we wait for all threads to be shut down before we do the leaked stream check.
(Details)
=> Unflake VCFPiperSuite

core/src/main/scala/io/projectglow/bgen/BgenFileFormat.scala, core/src/main/scala/io/projectglow/bgen/BigBgenDatasource.scala, core/src/main/scala/io/projectglow/common/logging/HlsEventRecorder.scala, core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/main/scala/io/projectglow/sql/BigFileDatasource.scala, core/src/main/scala/io/projectglow/transformers/normalizevariants/NormalizeVariantsTransformer.scala, core/src/main/scala/io/projectglow/transformers/pipe/PipeTransformer.scala, core/src/main/scala/io/projectglow/vcf/BigVCFDatasource.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala
Ensures that we only log one big VCF write per file, not per partition. For ease of use down the road, also simplifies the logging interface.
Events are propagated on the universe side.
=> Record one big VCF write event per file

core/src/main/scala/io/projectglow/vcf/AnnotationUtils.scala, core/src/main/scala/io/projectglow/vcf/VCFSchemaInferrer.scala, core/src/test/scala/io/projectglow/vcf/VCFSchemaInferrerSuite.scala
The annotation subfields parsed from `ANN` by https://github.com/projectglow/glow/pull/122 are unsafe to save to Parquet, as they may contain illegal characters (such as spaces). This PR removes spaces and dots (to keep them from being parsed as structs) from any subfield names to make them safe to save.
=> Make annotation column names safe

core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/test/scala/io/projectglow/plink/PlinkReaderSuite.scala
Calculates the byte location for a variant in a (PLINK) BED file as a `Long` to avoid integer overflow.
Addresses https://github.com/projectglow/glow/issues/133.
Successfully ran through the workflow described in the aforementioned issue.
=> Fix large PLINK file ingest

core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/main/scala/io/projectglow/plink/PlinkRowToInternalRowConverter.scala
Speeds up PLINK read by only converting the sample IDs to `UTF8String`s once, rather than for each genotype.
On the same cluster setup, I read from the 1KG PLINK files and materialized the DataFrame (by writing to a `noop` format). This change resulted in the runtime decreasing from 1.76 minutes to 1.18 minutes.
=> Speed up PLINK read

core/src/main/scala/io/projectglow/vcf/VCFOutputFormatter.scala, core/src/test/scala/io/projectglow/vcf/VCFPiperSuite.scala
We broke the VCF output formatter in https://github.com/projectglow/glow/pull/79 by not copying the unsafe rows; this resulted in each row of VCF output from the pipe transformer being equivalent.
Added sanity check for VCF piper.
=> Fix VCF output formatter

build.sbt, core/src/main/scala/io/projectglow/SparkShimBase.scala, core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala, core/src/main/scala/io/projectglow/sql/SqlExtensionProvider.scala, core/src/main/scala/io/projectglow/transformers/pipe/CSVInputFormatter.scala, core/src/main/scala/io/projectglow/transformers/pipe/CSVOutputFormatter.scala, core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/UnivocityGenerator.scala, core/src/main/shim/2.4/SparkShim.scala, core/src/main/shim/3.0/SparkShim.scala, core/src/test/scala/io/projectglow/SparkTestShimBase.scala, core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala, core/src/test/scala/io/projectglow/tertiary/AggregateByIndexSuite.scala, core/src/test/shim/2.4/SparkTestShim.scala, core/src/test/shim/3.0/SparkTestShim.scala
Source code changes so that we are ready for Spark 3.0, which includes some internal API refactoring and [behavior changes](https://spark.apache.org/docs/3.0.0-preview/sql-migration-guide.html).
Confirmed tests (`core_2_12/test`, `python_2_12/test`, and `docs_2_12_test`) will pass on Spark 3.0, which is built on Scala 2.12. To build Glow on Spark 3.0, do the following: 
- Modify `build.sbt `
+ `val sparkVersion = "3.0.0-preview2"`
+ In `core`:
- `Compile / unmanagedSourceDirectories += baseDirectory.value / "src" / "main" / "shim" / "3.0"`,
- `Test / unmanagedSourceDirectories += baseDirectory.value / "src" / "test" / "shim" / "3.0"`,
- [Download](https://www.apache.org/dist/spark/spark-3.0.0-preview2/) and `pip install pyspark-3.0.0.dev2.tar.gz`
=> Prepare for Spark 3.0

core/src/main/scala/io/projectglow/sql/optimizer/hlsOptimizerRules.scala
`Aggregate` has a different signature in DBR versus OSS Spark; this removes compatibility issues caused by https://github.com/projectglow/glow/pull/151.
(Details)
=> Aggregation signature rewrite

build.sbt
With the changes made in https://github.com/projectglow/glow/pull/155, the staged release tests broke as its compilation does not pull in the appropriate Spark test shims. This PR adds the Spark 2.4 test shims to the Scala sources used to compile the tests.
The staged 0.3.0 release tests pass (with the bumped stable version):
- stagedRelease_2_11/test
- stagedRelease_2_12/test
=> Fix staged release tests

.gitignore, core/src/main/scala/io/projectglow/bgen/BigBgenDatasource.scala, core/src/main/scala/io/projectglow/transformers/pipe/Piper.scala, core/src/main/scala/io/projectglow/vcf/BigVCFDatasource.scala, core/src/main/scala/org/apache/spark/sql/SQLUtils.scala, core/src/test/scala/io/projectglow/bgen/BgenWriterSuite.scala, core/src/test/scala/io/projectglow/transformers/pipe/CSVPiperSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFFileWriterSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFPiperSuite.scala
We currently have inconsistent behavior between the following tools that act on RDD partitions in the case that there are 0 partitions:
- Big BGEN writer
- Big VCF writer
- Pipe transformer
Now, we replace the underlying 0-row, 0-partition RDD with a 0-row, 1-partition RDD. This allows users to write big VCF/BGENs or pipe with the header alone. This will un-break our tests on [SPARK-30780](https://issues.apache.org/jira/browse/SPARK-30780), which causes empty DataFrames to (usually) be backed by an empty RDD with 0 partitions.
=> Allow 0 partitions in big VCF/BGEN writers and pipe transformer

build.sbt, core/src/main/scala/io/projectglow/SparkShimBase.scala, core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/UnivocityGenerator.scala, core/src/main/shim/2.4/SparkShim.scala, core/src/main/shim/3.0/SparkShim.scala
Spark 3 APIs have changed since `preview-2`. To make sure we stay up-to-date with the most recent version of Spark 3, I've added a resolver for the nightly snapshot builds so we can test against it.
The latest version of Spark 3 has a different API for its univocity parser, resulting in the creation of a new shim.
Ran tests on the Spark 3 nightly snapshot.
=> Part 2: Prepare for Spark 3

core/src/main/scala/io/projectglow/vcf/InternalRowToVariantContextConverter.scala, core/src/test/scala/io/projectglow/vcf/InternalRowToVariantContextConverterSuite.scala
Previously, we (I believe inadvertently) stored stringly typed info and format fields as Spark's `UTF8String`s when converting `InternalRow`s to `VariantContext`s. This could lead to the value changing over time if the Spark overwrites the buffer underlying the `UTF8String`. Instead, we should convert to plain ole `String`s when making VCs.
I verified that a problematic job is fixed by this patch.
=> Convert UTF8Strings to Strings before storing in VariantContext

core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala, core/src/test/scala/io/projectglow/vcf/VCFHeaderUtilsSuite.scala
Changes `VCFHeaderUtils.getUniqueHeaderLines` to read not only FILTER and INFO header lines, but also contig and filter lines. During disambiguation, performs a check that contig lines with the same ID have the same length. No such check occurs for FILTER lines.
=> Read unique contig and filter VCF header lines

core/src/main/scala/io/projectglow/vcf/VCFStreamWriter.scala, core/src/test/scala/io/projectglow/vcf/VCFStreamWriterSuite.scala
If the VCF input formatter's stream closes prematurely, it can break the writer when it closes. This wraps the writer's closing with a try-catch.
=> Wrap VCF writer closing with try-catch

core/src/main/scala/io/projectglow/sql/BigFileDatasource.scala
To avoid using visibility shims elsewhere, we should make the `SingleFileWriter` interface public.
(Details)
=> Make SingleFileWriter public

docs/source/tertiary/regression-tests.rst
The certs for rdocumentation.org are wrong, resulting in our link checker being broken
`SSLError(SSLCertVerificationError("hostname 'www.rdocumentation.org' doesn't match either of 'new.datacamp.com', '*.new.datacamp.com', 'datacamp.com', '*.datacamp.com'"))`
This PR replaces instances of rdocumentation.org with stat.ethz.ch/R-manual/.
(Details)
=> Replace rdocumentation links

core/src/main/scala/io/projectglow/transformers/pipe/CSVOutputFormatter.scala, core/src/main/scala/io/projectglow/transformers/pipe/Piper.scala, core/src/test/scala/io/projectglow/transformers/pipe/CSVPiperSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFPiperSuite.scala
Rather than forcing users to repartition/coalesce when using the VCF input formatter, it makes sense to not invoke the piped command for any empty RDD partitions.
This change assumes that any piped tool has no output if it has no data in the input, even if there are metadata (ie. VCF or CSV header).
Modified tests for the VCF and CSV pipers.
=> Do not pipe empty RDD partitions

.circleci/config.yml, docs/source/tertiary/regression-tests.rst
The stat.ethz.ch R manual is returning 403s and rdocumentation.org's cert issue was resolved, so I'm reverting https://github.com/projectglow/glow/pull/178. I also added the link checker to the nightly tests so we can resolve broken links ASAP and avoid spurious failures on PRs.
=> Address link check failures

.circleci/config.yml
Creates a cache for the Spark 3-based conda environment to avoid downloading PySpark 3 for every CircleCI build.
=> Cache conda env for Spark 3

core/src/main/scala/io/projectglow/vcf/TabixIndexHelper.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala, core/src/test/scala/io/projectglow/vcf/TabixHelperSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFHeaderUtilsSuite.scala
Users can use wildcards to directly read VCF files today, such as:
```
spark.read.format("vcf").load("vcf-dir/*.vcf.gz")
```
However, the VCF reader breaks if the user attempts to read directly from a directory containing tabix indices, such as:
```
spark.read.format("vcf").load("vcf-dir")
```
This PR tells the VCF reader to ignore tabix index files.
=> Ignore tabix index files when reading VCFs

core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala, core/src/test/scala/io/projectglow/vcf/VCFHeaderUtilsSuite.scala, test-data/vcf/missing_contig_length.vcf
With https://github.com/projectglow/glow/pull/173, VCF ingest now fails when merging files with contig lines that are missing the `length` field. This is resolved in newer versions of the HTSJDK as of https://github.com/samtools/htsjdk/pull/1418.
As we don't need contig and filter header lines for schema inference during VCF ingest, we can skip reading them entirely. This PR adds an option to skip reading non-schema header lines while reading unique header lines.
=> Do not read contig and filter header lines on VCF ingest

README.md
- Add hints for running python tests from IntelliJ
- Clarify that you must use Java 8
(Details)
=> Update README with IntelliJ hints

.circleci/config.yml, .gitignore, python/environment.yml
Previously uninstalling pyspark from the environment would fail because it was absent from the cache. We'll also get new pyspark updates this way, although the package we install may be immutable.
(Details)
=> Save conda cache before installing pyspark3 dev build

build.sbt
This PR removes gatk dependency from build.sbt. Standalone Picard dependency is added. 
(Details)
=> [HLS-425] Remove gatk dependency from build.sbt

docs/source/etl/variant-data.rst
The PLINK documentation is currently incorrect - we assume FAM files are delimited by spaces and BIM by tab, not the other way around.
(Details)
=> Fix PLINK documentation

core/src/main/scala/io/projectglow/sql/dsl/package.scala, core/src/main/scala/io/projectglow/sql/expressions/MeanSubstitute.scala
The mean substitution expression reused lambda variables in an unsafe way.
=> Fix mean substitution lambda variable usage

core/src/main/shim/3.0/SparkShim.scala
This reverts commit 6bf84356724df43e13a341ba851d0c7d648fc036.
=> Revert "Use full ExpressionInfo constructor (#209)"

README.md, build.sbt
Expose a `pytest` key for python projects that is a thin wrapper around the `pytest` CLI. This makes it possible to run a single suite, a single test from a single suite, etc. Additionally, I consolidated the test running logic between `python` and `docs`.
(Details)
=> Make it easier to run specific python tests

build.sbt, python/.style.yapf, python/environment.yml, python/glow/conftest.py, python/glow/functions.py, python/glow/glow.py, python/glow/tests/test_register.py, python/glow/tests/test_transform.py, python/render_template.py, python/setup.py, python/test_render_template.py
Adds yapf to check Python style. To format in place, call `sbt yapfAll`.
=> Add yapf to format Python files

python/glow/wgr/linear_model/functions.py, python/glow/wgr/linear_model/ridge_model.py, python/glow/wgr/linear_model/tests/test_functions.py, python/glow/wgr/linear_model/tests/test_ridge_regression.py
From @karenfeng:
In the case that the user does not know which `alpha` values to provide (eg. based on heritability estimates), we should support automatically generating them. These values do not work well in the case that the phenotypes are not on the scale of 1.
=> Generate inferred alphas

python/glow/wgr/linear_model/functions.py, python/glow/wgr/linear_model/ridge_model.py, python/glow/wgr/linear_model/tests/test_functions.py
Follows up on https://github.com/projectglow/glow/pull/242, with a minor refactor and a check that the added regex's are tolerant for chromosomes with underscores.
=> Add tests that regex's tolerate chromosomes with underscores

core/src/main/scala/io/projectglow/common/PythonUtils.scala, python/glow/conversions.py
The current method turns out to be quite slow. When I tried on a 5M sample dataset, converting a 10 col covariate matrix took over 10 minutes (I stopped waiting after that). This method is much faster because it only requires a single call between Python and Java.
- Verified that this works with large sample sizes on a cluster
- Timed locally:
```
def test_timing(spark):
arr = np.random.rand(10000)
d = dict(globals())
d.update(locals())
print(timeit.timeit('_convert_numpy_to_java_array(arr)', globals=d, number=100))
print(timeit.timeit('_convert_numpy_to_java_array_old(arr)', globals=d, number=100))
```
Output:
```
0.445821821
101.61667800699999
```
=> Faster conversion from python double array to java

core/src/main/scala/io/projectglow/sql/BigFileDatasource.scala, core/src/test/resources/META-INF/services/io.projectglow.sql.BigFileUploader, core/src/test/scala/io/projectglow/sql/BigFileDatasourceSuite.scala, core/src/test/scala/io/projectglow/sql/SingleFileWriterSuite.scala
To match the behavior in Spark, we should be creating a new Hadoop configuration: https://github.com/apache/spark/blob/9331a5c44baa79998625829e9be624e8564c91ea/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala#L113
This allows the user to pass configurations via the Spark runtime configurations (`spark.config`) or the writer options, rather than directly manipulating the Spark hadoop configs.
=> Pass new Hadoop configuration in BigFileDatasource

.circleci/config.yml, build.sbt, python/environment.yml
Sets the default build (locally and on CI/CD) to depend on Spark 3.0.0, which is now in GA.
=> Default build to Spark 3.0.0

python/glow/glow.py
`SQLContext.getOrCreate` is deprecated in Spark 3.0.0. This PR removes our usage of this API in the Glow transformer, as we can use the one in the input DataFrame.
`test_transform.py` should cover this.
=> Use SQL context from input DataFrame in transformer

docs/source/additional-resources/community-edition/community-edition.rst
The Databricks cluster libraries link has changed. This PR fixes the link.
Link check test.
=> Fix cluster libraries link

core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala
We missed this bit when we forked `TextBasedFileFormat`'s splitability conditions.
(Details)
=> Non-compressed VCFs should be splitable

docs/source/etl/variant-data.rst
Documents the validation stringency parameter when reading/writing VCF, related to #272.
Ran `make livehtml` to make sure the docs look reasonable.
=> Document validation stringency when reading/writing VCF

docs/source/tertiary/whole-genome-regression.rst, python/glow/wgr/linear_model/functions.py, python/glow/wgr/linear_model/tests/test_functions.py
Addresses #260 by generating alphas based on the number of unique headers with the labels removed.
=> Generate alphas with label-free headers

build.sbt, core/src/main/scala/io/projectglow/transformers/LiftOverVariantsTransformer.scala
This PR removed the usage of htsjdk.samtools.reference.ReferenceSequence.getBaseString on long sequences and replaces it with getBases followed by converting only the desired part of the byte array to string.
Before this change, on a small cluster the transformer took close to 2 hours to do liftover on 1000 genome chr22 vcf due to a lot of string allocation and GC. After this change, the liftover takes about 10min. 
(Details)
=> [HLS-627] Improve lift_over_variants performance

docs/source/etl/utility-functions.rst, docs/source/etl/variant-data.rst, docs/source/etl/variant-normalization.rst
Some of our docs pages were written before we generated Python functions for our various expressions. Now that we have a more thorough Python API, we should use it in the documentation examples.
Also, I clarified the conversion to a 0-based coordinate system when ingesting VCF files.
(Details)
=> Use python functions instead of string expressions in docs

core/src/test/scala/io/projectglow/bgen/BgenRowConverterSuite.scala
We need to use `map(_.copy())` every time we use `queryExecution.toRdd`, as `InternalRow`s are re-used (see https://github.com/apache/spark/blob/76330e029540fa7ff4311c682135efd8bf0804e5/sql/core/src/main/scala/org/apache/spark/sql/execution/QueryExecution.scala#L121). Without this, our tests failed when adaptive query execution (AQE) was enabled. I fixed this bug in our tests and added a regression test.
=> Fix BgenRowConverterSuite with AQE enabled

build.sbt, downversion-pyspark.txt
This PR modifies build.sbt to cross release glow for 
- Spark3 Scala 2.12 
- Spark2 Scala 2.12
- Spark2 Scala 2.11.
I ran a round of test release and all worked well. 
(Details)
=> Spark Cross Release

docs/source/conf.py
These pages are now gated by a captcha. It's unfortunate that our link checker doesn't work here since the GATK links are pretty important, but I don't think there's a way around.
(Details)
=> Disable gatk docs link checks

core/src/main/scala/io/projectglow/sql/expressions/FirthTest.scala, core/src/main/scala/io/projectglow/sql/expressions/LogisticRegressionGwas.scala, core/src/test/scala/io/projectglow/tertiary/LogisticRegressionSuite.scala, core/src/test/scala/io/projectglow/tertiary/NewtonIterationsStateSuite.scala, functions.yml, python/glow/functions.py
Previously we were not re-initializing the `beta` vector between genotypes for a given phenotype. This means that if one row results in a `NaN` beta, all successive rows will fail to converge.
(Details)
=> Re-initialize beta vector between genotypes in LogisticRegression

.circleci/config.yml, docs/dev/gen-nb-src.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/gff.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/lift-over.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/merge-vcf.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/normalizevariants.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/sample-qc-demo.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/splitmultiallelics-transformer.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/variant-data.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/variant-qc-demo.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/etl/vcf2delta.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/tertiary/binaryglowgr.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/tertiary/glowgr.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/tertiary/gwas.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/tertiary/pandas-lmm.py, docs/source/_static/zzz_GENERATED_NOTEBOOK_SOURCE/tertiary/pipe-transformer.py, python/environment.yml
Adds generated notebook sources for our documentation for easy diff-ability by converting from HTML to source code. Checks via CI that the generated sources are not out-of-date.
To generate a notebook source yourself:
- Update your conda environment with the new dependencies
- Configure your Databricks CLI
- Run `gen-nb-src.py` with the input HTML
Example of CI catching failures: https://app.circleci.com/pipelines/github/projectglow/glow/1646/workflows/58e2deeb-7036-468e-8975-bcc3115a04a0/jobs/3878
=> Generate notebook sources

core/src/main/scala/io/projectglow/sql/GlowConf.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala, core/src/main/scala/io/projectglow/vcf/VCFLineToInternalRowConverter.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala, docs/source/etl/variant-data.rst
The fast reader is used in production by several customers and returns results identical to the existing reader. Let's turn it on by default!
Validation notebooks:
https://shard-qa.staging.cloud.databricks.com/#notebook/1605172/command/1605577
https://dbc-fa2345f4-52df.cloud.databricks.com/#notebook/5807/command/5810
(Details)
=> Turn on fast reader by default

docs/source/etl/variant-data.rst
Our BGEN reader and writer assume that the first allele is the reference, and that following alleles are alternate alleles. Our PLINK reader assumes that the first allele is the alternate, and that the second allele is an alternate allele. This PR adds clarifying documentation.
Ran `make livehtml` to ensure the tip showed up.
=> Document BGEN/PLINK allele order

python/glow/wgr/linear_model/logistic_model.py, python/glow/wgr/linear_model/tests/test_logistic_regression.py
Changes how we handle covariates passed into binary GloWGR's transform function. Rather than handling it as a special case in `transform_loco`, pushes the replacement of the covariate matrix down to the transform function.
=> Ignore covariates in binary WGR transform for linear response

core/src/main/scala/io/projectglow/vcf/TabixIndexHelper.scala, core/src/test/scala/io/projectglow/vcf/TabixHelperSuite.scala
Fixes the logic for parsing whether a partition file overlaps with the tabix offsets. In particular, does not include a partitioned file as overlapping if it does not include the start position of the last tabix offset (even if it's within 0xFFFF), as it only contains the tail of the block and will trigger a failure when trying to read the GZIP block header.
During this exploration, we also learned that the BGZF codec seeks to the first BGZF header and reads through to the end of any block it has already started, whether or not it is within the limits of the partitioned file: https://github.com/apache/hadoop/blob/d4c8d4d4d203c934e8074b31289a28724c0842cf/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/input/Compress …
=> Address edge case with tabix offsets and partitioned files

conftest.py, python/glow/gwas/functions.py, python/glow/gwas/lin_reg.py, python/glow/gwas/log_reg.py, python/glow/gwas/tests/test_lin_reg.py, python/glow/gwas/tests/test_log_reg.py, python/glow/wgr/functions.py, python/glow/wgr/tests/test_pivot_for_gwas.py, python/glow/wgr/tests/test_reshape_for_gwas.py
Fitting all the null models and preparing the broadcast data could take a looooong time with many phenotypes and loco offsets. Let's use Spark!
I also sped up the `reshape_for_gwas` function.
(Details)
=> Parallelize null model fit for logistic regression

python/glow/gwas/approx_firth.py, python/glow/gwas/functions.py, python/glow/gwas/lin_reg.py, python/glow/gwas/log_reg.py, python/glow/gwas/tests/test_approx_firth.py, python/glow/gwas/tests/test_lin_reg.py, python/glow/gwas/tests/test_log_reg.py
- Add a `contigs` param for `linear_regression` and `logistic_regression`. When provided in conjunction with LOCO offsets, this indicates that we should only compute and broadcast driver side data for the selected contigs. From my tests, this is necessary with UKB sized datasets (otherwise Spark can OOM when serializing / deserializing the closure)
- Remove type checking for the offset parameter in the approximate firth correction. `nptyping` does not play nicely with optional params -- it previously raised an exception of the offset was `None`.
- Compute only the diagonal of the hat matrix in the approximate firth correction. The full matrix is size `n_samples x n_samples` and so cannot be materialized.
- Do not use `statsmodels` in the …
=> Regression function fixes / improvements

conftest.py, core/src/main/scala/io/projectglow/Glow.scala, core/src/main/scala/io/projectglow/sql/util/BGZFCodec.scala, core/src/main/scala/io/projectglow/vcf/BigVCFDatasource.scala, core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala, core/src/main/scala/org/hadoop_bam/util/GlowBGZFOutputStream.scala, core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala, core/src/test/scala/io/projectglow/sql/SqlExtensionProviderSuite.scala, docs/source/etl/sample-qc.rst, docs/source/getting-started.rst, docs/source/tertiary/whole-genome-regression.rst, python/glow/conftest.py, python/glow/glow.py, python/glow/tests/test_register.py
While running the example notebooks on a Databricks cluster, I noticed that some functions can fail with confusing analysis errors if the cluster has run a query (including showing tables) before `glow.register` was called. To improve the default behavior, I added a `new_session` parameter to `register` so that this error can't happen by default.
In addition, I updated the register method to decrease the columnar parquet reader's batch size by default, which is typically necessary for large cohorts. This matches what we do in the Databricks genomics runtime.
I will update the notebooks in a forthcoming notebook cleanup PR.
(Details)
=> Improve register

core/src/main/scala/io/projectglow/sql/dsl/package.scala, core/src/main/scala/io/projectglow/sql/expressions/MeanSubstitute.scala, core/src/test/scala/io/projectglow/tertiary/VariantQcExprsSuite.scala
Turns out that `mean_substitute` was accidentally `O(n^2)` in the worst case. We recomputed the mean for each missing element.
(Details)
=> Make mean_substitute faster

build.sbt
Hail tests require additional configuration to our normal tests. In addition, it can mess with the current Python setup (by relying on old pandas versions, etc.). To avoid Hail artificially breaking our tests, I broke out the tests during the release process so we can configure them individually.
Discovered spurious failures as a result of running a release; these changes un-broke the release.
=> Perform Hail tests separately during release

python/glow/gwas/functions.py
Switches to pandas-style verification.
This broke the linreg test in the GWAS notebook I was running as part of a release; this fix resolved the issue.
=> Fix broken covariate/phenotype validation

docs/source/etl/variant-data.rst
Fix Glow version in doc. There was no 0.7.0 release.
n/a
=> Fix Glow version in doc

codecov.yml
Increasing threshold for codecov to allow negligible changes to code testing coverage to pass tests
Example where this issue occurs:
https://github.com/projectglow/glow/pull/402
(Details)
=> adding codecov.yml

docker/databricks/build.sh, docker/databricks/dbr/dbr9.1/genomics/Dockerfile, docker/databricks/dbr/dbr9.1/minimal/Dockerfile, docker/databricks/dbr/dbr9.1/r/Dockerfile, docs/dev/jobs-config-hail.json, docs/dev/jobs-config.json
Update glow docker container to run on ubuntu 20.04 by default
To match Databricks runtime 9.x and above
(Details)
=> update docker container to run on ubuntu 20.04

docker/databricks/dbr/dbr9.1/genomics/Dockerfile
adding [bgenix](https://enkre.net/cgi-bin/code/bgen/dir?ci=trunk) to the Glow Dockerfile
The glow bgen writer does not index bgen files, 
so use the bgenix tool to index bgen files written to glow
(Details)
=> add bgenix tool to dockerfile

docker/databricks/dbr/dbr9.1/genomics/Dockerfile
Was having issues getting the R Package bigsnpr working in Databricks after switching to Ubuntu 20.04, and after adding bgenix into this container. 
Discussed this with the author of bigsnpr, https://github.com/privefl/bigsnpr/issues/279. And he rightly pointed out that there was no clear reason why the tool should fail to install. We tested manually installing in databricks and this worked.
I decided to swap the order in which bigsnpr is built in two ways,
1. relative to bgenix
2. relative to other R packages in the container
And this worked. Not sure why, but can't hurt to reorder just in case
(Details)
=> reorder dockerfile

docker/databricks/dbr/dbr9.1/genomics/Dockerfile
The current solution for [simulating genotypes](https://glow.readthedocs.io/en/latest/etl/data-simulation.html#simulate-genotypes) using Spark is fairly rudimentary. Fixing the installation of [Sim1000G](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2611-1) as a replacement so we can ramp up testing. Having the tool working with the Glow Docker Container makes it much easier to iterate
I was getting this issue:
`Loading required package: hapsim
Loading required package: MASS
Loading required package: stringr
Loading required package: readr
[#.......] Reading VCF file..
Warning in system("timedatectl", intern = TRUE) :
running command 'timedatectl' had status 1
Error : Unknown TZ /UTC
Some(<code …
=> Sim1000G installation patch

docker/databricks/build.sh, docker/databricks/dbr/dbr9.1/ganglia/Dockerfile, docker/databricks/dbr/dbr9.1/genomics-with-hail/Dockerfile, docker/databricks/dbr/dbr9.1/python/Dockerfile
Upgraded Hail version from 0.2.78 to 0.2.85 -> explicitly pinned this version
downgrading the version of numpy for the glow docker container. 
This is to avoid this issue here:
https://stackoverflow.com/questions/63761366/numpy-linalg-linalgerror-svd-did-not-converge-in-linear-least-squares-on-first
- [x ] Manual tests
ran all notebooks to ensure they still work
confirmed correct version of numpy was installed with docker container `projectglow/databricks-glow:1.1.2`
=> docker container update

docs/source/etl/lift-over.rst
fix broken link to liftOver notebook 
Also add a tip to the docs about handling custom chain files
- [x ] Manual tests
built docs locally by following the contributing guide:
https://glow.readthedocs.io/en/latest/contributing.html#improve-the-documentation
and confirmed that the html version of the notebook is rendering
=> fix broken liftOver notebook link in docs

.circleci/config.yml
Signed-off-by: David Castillo <d.v.castillo37@gmail.com>
Update the following orbs:
1. codecov/codecov@1.0.5 ==> codecov/codecov@3.2.2
2. circleci/jq@1.6.0 ==> circleci/jq@2.2.0
Based on looking at the resource utilization of all CircleCI workflows, I made the following optimizations for credit consumption:
1. For the job, `check-docs`, the overall resource utilization for both RAM/CPU is much lower than this resource class is intended for (screenshots included). I have added an additional resource class size of medium+ to minimize credit consumption. 
2. For the job, `all-notebook-tests`, the overall resource utilization for both RAM/CPU is much lower than this resource class is intended for (screenshots included). I have added an additional resource class size of medium+ to minimize …
=> Optimize CircleCI Config

core/src/main/scala/io/projectglow/vcf/VCFLineToInternalRowConverter.scala, core/src/main/scala/io/projectglow/vcf/VariantContextToInternalRowConverter.scala, core/src/test/scala/io/projectglow/vcf/VCFDatasourceSuite.scala, test-data/vcf/test_withInfGenotype.vcf, test-data/vcf/test_withInfQual.vcf, test-data/vcf/test_withNanGenotype.vcf
Issue raised here: https://github.com/projectglow/glow/issues/517
In short, the VCF allows infinity/nan that follow this regex `^[-+]?(INF|INFINITY|NAN)$ case insensitively`
The code that parses the INFO and genotype columns do not allow the full range of valid values.
Verified that unit tests failed before applying changes.
And unit tests passed after applying my changes.
=> Fix Infinity/NaN parsing to allow full set of values from VCF specification

core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala
VCF reader does not support special characters such as whitespaces, but json and csv datasource readers do.
Right now a user would have to replace whitespaces with underscores, which may be time consuming if the number of files to convert is large.
https://github.com/projectglow/glow/issues/474
Will need to write unit tests to check a path with whitespaces
(Details)
=> Support whitespaces for variant datasources

docs/source/etl/gff.rst
Update documentation for GFF schema for `Alias` field
According to https://glow.readthedocs.io/en/latest/etl/gff.html#schema. `Alias` is defined as `string`. However, in the actual source code, it's defined as an array of `string`: https://github.com/projectglow/glow/blob/8b0bcd6b2f7320c3a5bd186bdcfa4707af303b47/core/src/main/scala/io/projectglow/common/schemas.scala#L171
Updating the documentation so it is matching exactly how it's internally represented. 
(Details)
=> Update documentation for GFF schema for Alias field

docs/source/conf.py, python/setup.py
The linkcheck had been occasionally hanging because 1) the 1kg ftp listing was flaky 2) there wasn't an explicit timeout set (although I thought there was a default according to sphinx docs...)
Also fixed an error in setup.py
(Details)
=> Add explicit linkcheck timeout; ignore flaky 1kg link; fix setup.py syntax error

.github/workflows/scala-dependency.yml
Github's dependency page is still showing the dependencies we've updated since last release. Hopefully this will resolve it.
(Details)
=> Don't report staged release dependencies

python/glow/gwas/tests/test_log_reg.py
Sometimes the tests were failing because of perfect separation. Let's try increasing the number of samples to avoid this.
(Details)
=> Try avoiding perfect separation in logistic regression tests

build.sbt
Assembly jars built with coverage on expect scoverage to be available at runtime.
(Details)
=> Only enable scoverage during tests

core/src/main/scala/io/projectglow/transformers/pipe/Piper.scala
In unit tests we run programs that don't read from stdin. The process exits before the stream can be closed.
(Details)
=> Suppress exception when closing stdin writer in pipe transformer

core/src/main/scala/io/projectglow/sql/expressions/LogisticRegressionExpr.scala, core/src/main/scala/org/apache/spark/sql/catalyst/expressions/QuinaryOptionalExpression.scala, core/src/test/scala/org/apache/spark/sql/catalyst/expressions/QuinaryOptionalExpressionSuite.scala
While testing the staged release, I found a naming collision between the quinary expression in Glow and the version that was later released in Spark. This could cause errors at runtime.
(Details)
=> [SPARK4] Rename quinary expression in Glow

.github/workflows/staging-release.yml
Twine doesn't natively support token fetching
(Details)
=> Use github action for PyPI publishing

.github/workflows/tests.yml, build.sbt, core/src/main/scala/io/projectglow/TestAssemblyJar.scala, core/src/main/scala/io/projectglow/sql/expressions/glueExpressions.scala, core/src/main/scala/io/projectglow/transformers/splitmultiallelics/VariantSplitter.scala, core/src/test/scala/io/projectglow/transformers/splitmultiallelics/VariantSplitterSuite.scala, functions.yml, project/plugins.sbt, python/render_template.py
- Fix Glow assembly jar
- Move colex order function to SQL
- Replace functions that aren't implemented in Photon
- Modifying splitter to avoid any copying or manipulation of the genotype struct when not splitting
Manual testing to make sure everything runs in Photon now
=> Make variant splitter work with Photon

python/glow/gwas/functions.py
modify opt_einsum.contract for compatibility with the [latest release](https://github.com/dgasmith/opt_einsum/commit/c15aec2c7dbbcaf5b9790b980f699bf295baa7d9#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05R6)
=> updating einsum contract for compatibility
