- build.sbt
- version.sbt
To publish to Maven Central, we need to have developers in the pom.
(Details)
> Add developers

- LICENSE.txt
- NOTICE.txt
Resolves #27.
Signed-off-by: Frank Austin Nothaft <frank.nothaft@databricks.com>
> Update license to Apache 2.0 license.

- build.sbt
The scala incremental compiler can be flaky, so for reproducible builds it's important that we clean before testing and uploading artifacts.
(Details)
> Clean before pushing artifacts

- build.sbt
> Update adam dependency version to 0.29.0

- CODE-OF-CONDUCT.md
Resolves #30.
(Details)
(Details)
> Add contributor covenant code of conduct

- core/src/main/scala/io/projectglow/sql/expressions/LogisticRegressionExpr.scala
- core/src/main/scala/io/projectglow/sql/expressions/LogisticRegressionGwas.scala
- core/src/test/scala/io/projectglow/tertiary/LogisticRegressionSuite.scala
- docs/source/tertiary/regression-tests.rst
Adds docs for logistic regression.
`make livehtml`
> Logistic regression docs

- .circleci/config.yml
- README.md
Adds code coverage. CircleCI will upload coverage results to CodeCov, which will make sure the coverage does not drop too far in a PR. Also adds a badge to the README.
> Add codecov

- version.sbt
Automated changes from `sbt release`.
Verified the release on our internal Databricks as well as a PySpark shell.
> Release 0.1.2

- core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala
#59 broke master because CircleCI tests only the PR branch, not the PR branch + master.
I'll work on a followup that merges master into the PR branch as a CI step.
(Details)
> Unbreak build

- docs/source/tertiary/pipe-transformer.rst
Adds documentation for pipe cleanup.
`make livehtml` looks good
> Add pipe cleanup docs

- .circleci/config.yml
- .gitignore
- build.sbt
Improve CI by:
- [Collecting test metadata](https://circleci.com/docs/2.0/collect-test-data/) in order to pinpoint flaky/slow suites.
- Parallelizes Scala suites (by runtime) across CircleCI containers. This decreases the full test time from 11 minutes to 7 minutes.
See more at https://circleci.com/gh/projectglow/glow.
> CI improvements

- docs/source/etl/variant-data.rst
> Remove merge conflict from plink docs

- docs/source/tertiary/regression-tests.rst
Should be self explanatory!
Wrote a new doc test
> Firth regression docs

- docs/source/blogs/variant-normalization-blog/variant-normalization-blog.rst
Updates the link to variant normalization doc in variant normalization blog after #101
(Details)
> Update the link to variant normalization doc in variant normalization blog

- core/src/main/scala/io/projectglow/vcf/VCFFileFormat.scala
- core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala
- core/src/test/scala/io/projectglow/vcf/VCFHeaderUtilsSuite.scala
Previously we read VCF headers in parallel but merged all of the lines into a set on the driver. When there are many VCF files that each contain many header lines, this can become a bottleneck. Now, we create this set in parallel.
(Details)
> Merge VCF header lines in parallel

- docs/source/conf.py
Tests have been failing intermittently because of connection errors from the linkchecker. I can visit the site directly.
(Details)
> Don't check links from oxford academic journals

- .circleci/config.yml
The CircleCI build is broken: https://app.circleci.com/pipelines/github/projectglow/glow/977/workflows/73aac552-2219-4b49-a9a1-d58077d812f0/jobs/1560.
The issue was resolved by downgrading our installed version of conda.
> Fix Spark 3 CI

- core/src/main/shim/3.0/SparkShim.scala
Use the full ExpressionInfo constructor.
(Details)
> Use full ExpressionInfo constructor

- docs/source/conf.py
> Ignore link check failures from sequenceontology.org

- core/src/main/scala/io/projectglow/common/logging/HlsEventRecorder.scala
- core/src/main/scala/io/projectglow/common/logging/HlsUsageLogging.scala
- python/glow/logging/__init__.py
- python/glow/logging/hlseventlogger.py
- python/glow/wgr/linear_model/ridge_model.py
This PR adds capability to log usage of WGR ridge_reduce and ridge_regression fit and transform functions.  
(Details)
> Log WGR events

- docs/source/additional-resources/community-edition/community-edition.rst
- docs/source/blogs/glowgr-blog/glowgr-blog.rst
Fixes up some linkcheck errors and redirects. Also fixes the CE setup instructions to point to the right steps.
Checked that the modified links point to the expected locations.
> Fix linkcheck errors

- python/glow/gwas/linear_regression.py
- python/glow/gwas/tests/test_linear_regression.py
Two usability improvements. I checked to see if using float32s makes any performance difference. It doesn't seem to make much of a difference with openblas, although it did decrease peak memory usage some.
(Details)
> Accept different datatypes, values column expression for linear regression

- docs/source/etl/variant-data.rst
Addresses #333. Thanks for bringing this up @djemec!
> Clarify ref/alt allele in PLINK docs

- README.md
> Add instructions to test code on a Databricks cluster

- .circleci/config.yml
- build.sbt
Exclude formatting on a file during build.
> Do not yapf build/lib/glow/functions.py

- version.sbt
Release v1.0.0. There are now in [Maven Central](https://search.maven.org/search?q=g:io.projectglow) and [pypi](https://pypi.org/project/glow.py/).
> Release v1.0.0

- core/src/main/scala/io/projectglow/Glow.scala
- core/src/test/scala/io/projectglow/GlowSuite.scala
- docs/source/conftest.py
- docs/source/etl/gff.rst
- docs/source/etl/hail.rst
- docs/source/etl/lift-over.rst
- docs/source/etl/merge.rst
- docs/source/etl/sample-qc.rst
- docs/source/etl/utility-functions.rst
- docs/source/etl/variant-data.rst
- docs/source/etl/variant-normalization.rst
- docs/source/etl/variant-splitter.rst
- docs/source/tertiary/pipe-transformer.rst
- docs/source/tertiary/regression-tests.rst
- docs/source/tertiary/whole-genome-regression.rst
Signed-off-by: Henry Davidge <henry@davidge.me>
We were accidentally registering the codec configuration to the old Spark session.
(Details)
> Fix bgz registration

- .circleci/config.yml
- docs/dev/run-nb-test.py
Updates the CircleCI config to run changed notebook tests on PRs; previously, we ran all notebook tests nightly.
Tested locally.
Confirmed that CircleCI job is triggered.
> Test changed notebooks in branches

- docs/README.md
Signed-off-by: wbrandler <william.brandler@databricks.com>
Made the docs readme more step-by-step
(Details)
> update docs README.md

- docs/source/tertiary/whole-genome-regression.rst
- python/glow/gwas/approx_firth.py
- python/glow/gwas/lin_reg.py
- python/glow/gwas/log_reg.py
Now that the regenie method has been published in _Nature Genetics_,
updated the links to the paper in the docs and the source code
(Details)
> Update regenie paper links

- .circleci/config.yml
- docs/dev/run-nb-test.py
Removing the init script, replacing with docker container
Also changing the workspace for the docs integration test
(Details)
> remove init script from nb test

- docker/databricks/build.sh
- docker/databricks/dbr/dbr9.1/genomics-with-hail/Dockerfile
bumping the hail version to 0.2.78
(Details)
> bump hail version

- docs/source/contributing.rst
- docs/source/etl/data-simulation.rst
- docs/source/tutorial.rst
Fixing the relative notebook paths as per,
https://github.com/readthedocs/readthedocs.org/issues/8682
`.. notebook:: . tertiary/1_quality_control.html`
not:
`.. notebook:: .. tertiary/1_quality_control.html`
Also fixed some minor typos / wording
(Details)
> Fix notebook paths

- docs/source/etl/hail.rst
- docs/source/getting-started.rst
fixing links to databricks docs that are broken after recent updates
(Details)
> fix broken links

- .circleci/config.yml
- docs/source/tutorial.rst
Setting explicit guidelines in the Glow GWAS tutorial about when to use the Regenie algorithm.
This will help clear up confusion from users about when and how to use Glow for GWAS.
Also changed the circleci configs to stop continuous integration jobs from failing.
(Details)
> Explain regenie's domain of applicability

- README.md
Track dockerhub pulls directly on the README
- [x ] Manual tests
checked the links work
> Track dockerhub

- .circleci/config.yml
updating as per circleci ticket [#105456](https://support.circleci.com/hc/requests/105456))
(Details)
> update legacy convenience image

- .circleci/config.yml
- GIT-PROCESS.md
- docker/databricks/build.sh
- docker/databricks/dbr/dbr9.1/dbfsfuse/Dockerfile
- docker/databricks/dbr/dbr9.1/genomics-with-glow/Dockerfile
- docker/databricks/dbr/dbr9.1/genomics-with-hail/00-hail.conf
- docker/databricks/dbr/dbr9.1/genomics-with-hail/Dockerfile
- docker/databricks/dbr/dbr9.1/genomics/Dockerfile
- docker/databricks/dbr/dbr9.1/minimal/Dockerfile
- docker/databricks/dbr/dbr9.1/python/Dockerfile
- docker/databricks/dbr/dbr9.1/r/Dockerfile
- docker/databricks/dbr/dbr9.1/r/Rprofile.site
- docker/databricks/dbr/dbr9.1/standard/Dockerfile
- docs/source/getting-started.rst
- docs/source/tertiary/spark-workflow-orchestrator.rst
Updated reference to DBFS API documentation to https://docs.databricks.com/dev-tools/api/latest/dbfs.html
> Documentation fixes for DBFS API 

- .github/workflows/scala-dependency.yml
In addition to the Scala Steward automatic dependency update PRs, this will alert us to vulnerabilities
(Details)
> Report scala dependency graph

- .gitignore
- .vscode/settings.json
> Ignore .vscode directory

- .github/workflows/scala-dependency.yml
The sbt dependency update job didn't ignore them when specified in camel case. Let's see if this works.
(Details)
> Make ignored modules lower case

- .circleci/config.yml
- .github/workflows/scala-dependency.yml
- CONTRIBUTING.md
- GIT-PROCESS.md
- README.md
- docs/dev/run-nb-test.py
- docs/source/contributing.rst
> Rename things from master to main

- bin/build
- build.sbt
- python/environment.yml
- python/setup.py
> Add script for simple building and installation

- build.sbt
- conftest.py
- core/src/main/resources/META-INF/services/org.apache.spark.sql.SparkSessionExtensionsProvider
- core/src/main/scala/io/projectglow/Glow.scala
- core/src/main/scala/io/projectglow/sql/SqlExtensionProvider.scala
- core/src/test/scala/io/projectglow/sql/GlowBaseTest.scala
- core/src/test/scala/io/projectglow/sql/SqlExtensionProviderSuite.scala
- docs/source/conftest.py
- python/glow/conftest.py
- python/glow/tests/test_register.py
> Put function registration in a service provider

- .github/workflows/tests.yml
- core/src/main/scala/io/projectglow/Glow.scala
- core/src/main/scala/io/projectglow/sql/expressions/LiftOverCoordinatesExpr.scala
- core/src/test/scala/io/projectglow/plink/PlinkReaderSuite.scala
> [WIP] Migrate tests to github actions

- README.md
> Add status badge for github tests

- .github/workflows/cut-release.yml
> Update cut release action

- .github/workflows/cut-release.yml
> Fix release workflow

- .github/workflows/cut-release.yml
> make a pr to update version during release

- .github/workflows/cut-release.yml
- build.sbt
> Update Python version file in cut release job

- .github/workflows/tests.yml
- python/spark-4-environment.yml
> [SPARK4] Upload runnable artifacts as part of CI

- .readthedocs.yml
> Tell readthedocs to use conda

- README.md
- docs/source/customizing/custom-patches.rst
- docs/source/customizing/databricks-environment.rst
- docs/source/customizing/index.rst
- docs/source/getting-started.rst
- docs/source/index.rst
Also slightly refactor documentation to put this information alongside instructions for customizing Databricks environments.
(Details)
> Add documentation for maintaining private patches and rebasing on OSS Glow

- .github/workflows/staging-release.yml
> Fix default shell in release job

- .github/workflows/staging-release.yml
So that the workflow file comes from main
(Details)
> Choose release tag in staging job

- .github/workflows/staging-release.yml
> Explicity call sbt exit in staging release job

- .github/workflows/staging-release.yml
The file contains configuration and not just credentials.
(Details)
> Don't clobber sonatype config

- build.sbt
- python/setup.py
For some reason `setuptools` in conda is a little different. Hopefully this change will fix the conda build.
(Details)
> Update Python build

- .github/workflows/production-release.yml
- .github/workflows/staging-release.yml
- RELEASE.md
- python/README.rst
Also update the PyPI readme to point to Github actions instead of circle ci.
(Details)
> Document release process

- .github/PULL_REQUEST_TEMPLATE
- .github/workflows/tests.yml
- RELEASE.md
So that any changes won't break forward compatibility.
(Details)
> Always run Spark 4 tests

- RELEASE.md
> Address @a0x8o's comments on the release process

- .github/PULL_REQUEST_TEMPLATE
- .github/workflows/tests.yml
The snapshot build doesn't seem stable enough yet.
> Don't always run Spark 4.0 tests

- docs/source/conf.py
Checking biorxiv links has been flaky
> Retry doc linkchecks

- core/src/main/scala/io/projectglow/vcf/VCFHeaderUtils.scala
- core/src/test/scala/io/projectglow/vcf/VCFFileWriterSuite.scala
- docs/source/etl/variant-data.rst
> Add option to manually specify sample ids

- core/src/main/scala/io/projectglow/functions.scala
- core/src/main/scala/io/projectglow/sql/expressions/glueExpressions.scala
- core/src/test/scala/io/projectglow/tertiary/VariantUtilExprsSuite.scala
- functions.yml
- python/glow/functions.py
Added function. Using interpolation method R7 from https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample. This is the same default as excel, R, and Julia.
> Function to get quantiles of array
